version: '2.4'

services:
  nextjs:
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - ./:/home/nextjs/app
    environment:
      - NODE_ENV=development
